
export default [
    {
        label:'首页',
        key:'home',
        icon:'appstore',
        isPublic:true,
    },
    {
        label:'商品',
        key:'products',
        icon:'appstore', 
        children:[
            {
                label:'品类管理',
                key:'category',
                icon:'appstore'
            },{
                label:'商品管理',
                key:'product',
                icon:'appstore',
            }
        ]
    },
    {
        label:'用户管理',
        key:'user',
        icon:'appstore'
    },
    {
        label:'角色管理',
        key:'role',
        icon:'appstore'
    },
    {
        label:'图形图表',
        key:'charts',
        icon:'appstore',
        children:[
            {
                label:'柱形图',
                key:'bar',
                icon:'appstore'
            },{
                label:'折线图',
                key:'line',
                icon:'appstore'
            },{
                label:'饼图',
                key:'pie',
                icon:'appstore'
            }
        ]
    },
]